export const GlobalCallTypes = {
  NEW_FILE: 'NEW_FILE',
  OPEN_FILE: 'OPEN_FILE',
  SAVE_FILE: 'SAVE_FILE',
  UNDO: 'UNDO',
  REDO: 'REDO',
  SELECT_ALL: 'SELECT_ALL',
  MODIFY_CONTENT: 'MODIFY_CONTENT',
}